CPP = g++
CFLAGS = -std=gnu++23 -Wall -O2 -Iinclude

TARGET = convex_hull

all: $(TARGET)

convex_hull: Quest_3a.cpp
	$(CPP) $(CFLAGS) -o ConvexHull Quest_3a.cpp ConvexHull.cpp

clean:
	rm -rf ConvexHull
