CPP = g++
CFLAGS = -Wall -O2 -std=gnu++23
TARGET = test_interval_tree

all: $(TARGET)

test_interval_tree: test_interval_tree.cpp
	$(CPP) $(CFLAGS) -o test_interval_tree test_interval_tree.cpp

clean:
	rm -rf test_interval_tree
